config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :appeals
  get 'welcome/index'

  root to: 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/appeal.rb
class Appeal < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true,
                    length: {minimum: 2}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :appeals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/appeals_controller.rb
class AppealsController < ApplicationController
  respond_to :html, :xml
  before_filter :authenticate_user!
  after_filter :verify_policy_scoped, :only => :index
  # after_action :verify_authorized, :except => :index
 # before_filter :authorize, :except => [:index, :new]

  def index
    @appeals = Appeal.all
    @posts = policy_scope(Appeal)
    # binding.pry
    respond_with(@appeals)
  end

  def show
    @appeal = Appeal.find(params[:id])
    authorize @appeal, :update?
    @appeal.publish!
    respond_with(@appeal)
  end

  def new
    @appeal = Appeal.new
    @posts = policy_scope(Appeal)
    respond_with(@appeal)
  end

  def edit
    @appeal = Appeal.find(params[:id])
    respond_with(@appeal)
  end

  def create
    # render plain: params[:appeals].inspect
    # @user = User.find(params[:user_id])
    @appeal = Appeal.new(appeal_params)
    # @user = current_user
    # @appeal = @user.appeals.create(appeal_params)

    if @appeal.save
      flash[:notice] = 'Well saved appeal'
    end
    respond_with(@appeal)
  end

  def update
    @appeal = Appeal.find(params[:id])

    if @appeal.update_attributes(appeal_params)
      flash[:notice] = 'Saving is success'
    end
    respond_with(@appeal)
  end

  def destroy
    respond_with(@appeal)
  end

  private
  def appeal_params
    # params.require(:appeal).permit(:name, :email, :issue_type, :title, :text)
    binding.pry
    params.require(:appeal).permit(policy(Appeal).permitted_attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # helper_method :admin?

  # def current_user
   #  @acurrent_user ||= Admin.find(session[:user_id])
  # end

  # protected
  # def admin?
    # current_user.role == "admin"
  # end

  # def authorize
    # unless admin?
      # flash[:notice] = 'Unathirozed access'
      # redirect_to root_path
      # false
    # end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/appeal_helper.rb
module AppealHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/appeals/_form.html.haml
= form_for @appeal do |a|

  - if @appeal.errors.any?
    #error_explanation
      %h2
        = pluralize(@appeal.errors.count, "error")
        prohibited this appeal from being saved:
      %ul
        - @appeal.errors.full_messages.each do |msg|
          %li= msg

  %p
    = a.label :name
    %br
    = a.text_field :name

  %p
    = a.label :email
    %br
    = a.text_field :email

  %p
    = a.label :issue_type
    %br
    = a.select(:issue_type,[['Technical Issue', 'Technical Issue'],
                            ['Billing Issue', 'Billing Issue'],
                            ['General Issue', 'General Issue']])

  %p
    = a.label :title
    %br
    = a.text_field :title

  %p
    = a.label :text
    %br
    = a.text_area :text

  - if user_signed_in?
    - if current_user.admin?
      %p
        = a.label :status
        %br
        = a.select(:status,[['Open', 'Open'],
                          ['Resolved', 'Resolved'],
                          ['Closed', 'Closed']])
  %p
    - if policy(@posts).any?
      = link_to "New post", new_appeal_path
  %br
  %p
    = a.submit 'Save Appeal'
  %br

app/views/appeals/edit.html.haml
%h1 Edit your appeal:

= render 'form'

app/views/appeals/index.html.haml
%h1 Customer Appeals:

%table
  %tr
    %th Name|
    %th E-mail|
    %th Issue Type|
    %th Title|
    %th Text|
    %th Status|
    %th Section|
  - @appeals.each do |a|
    %tr
      %td= a.name
      %td= a.email
      %td= a.issue_type
      %td= a.title
      %td= a.text

      - if current_user.admin?
        %td= a.status
        %td= a.section

      %td= link_to 'Edit', edit_appeal_path(a)

app/views/appeals/new.html.haml
%h1 Typing the form:

= render 'form'

app/views/appeals/show.html.haml
%p
  %strong Name:
  = @appeal.name

%p
  %strong E-mail:
  = @appeal.email

%p
  %strong Issue Type:
  = @appeal.issue_type

%p
  %strong Title:
  =@appeal.title
%p
  %strong Text:
  =@appeal.text

  =link_to 'new appeal', new_appeal_path
- if not current_user.user? == @appeal
  = link_to 'edit appeal', edit_appeal_path(@appeal)
%br
- if current_user.admin?
  %p
    %strong Status:
    =@appeal.status
  %br
  %p
    %strong Section:
    =@appeal.section
  %br
  = User.count
  = link_to 'Users:', users_path
  registered

app/views/layouts/application.html.haml
!!!
%html
%head
  %title CustomerSystem
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %p.notice
    = notice
  %p.alert
    = alert
  .user_nav
    -if user_signed_in?
      Signed in as
      = current_user.email
      Not you?
      = link_to "Sign out", destroy_user_session_path, :method => :delete
    -else
      = link_to "Sign up", new_user_registration_path
      or
      = link_to "sign in", new_user_session_path
  = yield

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/welcome/index.html.haml
%h1
  Hello, dear Customer
  = link_to 'please type the form', :controller => :appeals, :action => :new